<?php
const AUTO_GENERATED = "[AUTO_GENERATED]_";
const PATH_PRODUCTION_INJECTION = AUTO_GENERATED . 'PRODUCTION_INJECTION';
const PATH_FOLDER_JAVASCRIPT_CONG = "JAVASCRIPT/CONG";
const PATH_FOLDER_JAVASCRIPT_SITE_DATA = "JAVASCRIPT/SITE_DATA";
const FILE_CONG_JS = "CONG_JS";
const FILE_CONG_JS_INJECTION = "CONG_JS_INJECTION";
const SIGNAL_OF_PATH_CONG_JS_COMBINE_ALL_IN_FILE_CONG_JS_INJECTION_FOR_REPLACE = "SIGNAL_OF_PATH_CONG_JS_COMBINE_ALL_IN_FILE_CONG_JS_INJECTION_FOR_REPLACE";
//
const PATH_FOLDER_CONFIGS = "_CONFIGS";
const FILE_0_ANY_SITE_ALLOW_LIST = "0_ANY_SITE_ALLOW_LIST.txt";
const FILE_1_DEVELOP_SITE_LIST = "1_DEVELOP_SITE_LIST.txt";
const FILE_0_ANY_SITE_TEXT_JS = "0_ANY_SITE.js";
//
const PATH_FOLDER_CSS = "CSS";
const FILE_CSS_ALL = "CSS_ALL.css";